services:
  scraper:
    build: .
    ports:
      - "3002:3000" # Cambiado de 3001 a 3002 para evitar conflicto
      - "6085:6080" # Cambiado de 6080 a 6085 para evitar posibles conflictos
    environment:
      - PORT=3000 # Puerto en el que la aplicación escuchará
      - HEADLESS=false # Configurar como false para poder ver el navegador en VNC
      - RESOLUTION=1366x768x24 # Resolución del navegador virtual
      - NOVNC_PORT=6080 # Puerto explícito para noVNC
      - DISPLAY=:99
      - N8N_WEBHOOK_URL=https://n8n.sitemaster.lat/webhook/leotest # URL del webhook de n8n
    restart: unless-stopped
    # Necesario para ejecutar Chrome en Docker
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined # Necesario para Chrome en Docker
    # Volúmenes para persistir datos, logs y montar los scripts
    volumes:
      - ./:/app # Monta el directorio raíz del proyecto al directorio /app del contenedor
      - /app/node_modules # Evita que node_modules local sobrescriba el del contenedor
      - ./logs:/app/logs
      - /tmp/.X11-unix:/tmp/.X11-unix # Comparte el socket X11
    shm_size: 2gb # Memoria compartida suficiente para Chrome
    ipc: host # Permite compartir memoria entre procesos
